#!/usr/bin/env python3
"""
make_targets.py — Expand CIDR prefixes into a sampled list of IPs

Input:  text file with one CIDR prefix per line (e.g. 116.202.0.0/16)
Output: targets.txt with sampled IPs (one per /22 by default)

Usage:
    python3 make_targets.py hetzner-prefixes.txt
    python3 make_targets.py hetzner-prefixes.txt --sample-at 24
"""

import argparse
import ipaddress
import sys
from pathlib import Path


def sample_prefix(prefix: ipaddress.IPv4Network, sample_prefix_len: int) -> list[str]:
    """
    Take a CIDR prefix and return one sample IP per subnet at sample_prefix_len.

    Example: prefix=116.202.0.0/16, sample_prefix_len=22
      -> /16 contains 16 distinct /22 subnets
      -> returns one IP (host .10) from each
    """
    if prefix.prefixlen >= sample_prefix_len:
        # The prefix is smaller than the sampling unit; just one sample
        return [str(prefix.network_address + 10)]

    samples = []
    for subnet in prefix.subnets(new_prefix=sample_prefix_len):
        # Host .10 is usually a valid assignable host (avoiding gateway .1)
        samples.append(str(subnet.network_address + 10))
    return samples


def main():
    parser = argparse.ArgumentParser(description="CIDR prefixes -> sampled IPs")
    parser.add_argument("input", help="Input file containing CIDR prefixes")
    parser.add_argument(
        "-o", "--output", default="targets.txt",
        help="Output file (default: targets.txt)"
    )
    parser.add_argument(
        "-s", "--sample-at", type=int, default=22,
        help="Sample at which prefix length? Default: 22 (one IP per /22)"
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"[ERROR] File not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    all_samples = []
    skipped = 0

    with input_path.open() as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            try:
                net = ipaddress.IPv4Network(line, strict=False)
                samples = sample_prefix(net, args.sample_at)
                all_samples.extend(samples)
            except ValueError as e:
                print(f"[WARN] Ignoring invalid prefix '{line}': {e}", file=sys.stderr)
                skipped += 1

    # Deduplicate in case prefixes overlap
    unique = sorted(set(all_samples), key=lambda x: ipaddress.IPv4Address(x))

    with open(args.output, "w") as f:
        f.write(f"# Generated by make_targets.py\n")
        f.write(f"# Source: {input_path.name}\n")
        f.write(f"# Sampling: one IP per /{args.sample_at}\n")
        f.write(f"# Total: {len(unique)}\n\n")
        for ip in unique:
            f.write(f"{ip}\n")

    print(f"[OK] Wrote: {args.output}")
    print(f"[*]  Unique IPs: {len(unique)}")
    if skipped:
        print(f"[!]  Skipped invalid prefixes: {skipped}")


if __name__ == "__main__":
    main()
